Document: sipp
Title: Debian sipp Manual
Author: <insert document author here>
Abstract: This manual describes what sipp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sipp/sipp.sgml.gz

Format: postscript
Files: /usr/share/doc/sipp/sipp.ps.gz

Format: text
Files: /usr/share/doc/sipp/sipp.text.gz

Format: HTML
Index: /usr/share/doc/sipp/html/index.html
Files: /usr/share/doc/sipp/html/*.html
